# Set up mount points.

- name: create mounts
  mount:
    path: "/media/{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs4
    backup: yes
    state: mounted
    opts: ro,_netdev,auto
  loop:
    - { path: "nas_movies", desc: "Movies on NAS", src: "{{ nas_movies }}"}
    - { path: "nas_series", desc: "Series on NAS", src: "{{ nas_series }}"}
    - { path: "drobo_movies", desc: "Movies on Drobo", src: "{{ drobo_movies }}"}
    - { path: "drobo_series", desc: "Series on Drobo", src: "{{ drobo_series }}"}
    - { path: "drobo_pictures", desc: "Pictures on Drobo", src: "{{ drobo_pictures }}"}
    - { path: "drobo_music", desc: "Music on Drobo", src: "{{ drobo_music }}"}

