# Modify hosts file

- name: modify hosts file
  template:
    src: hosts.conf.j2
    dest: "{{ config_dir }}/hosts.conf"
    follow: yes

- name: create hostname file
  template:
    src: hostname.j2
    dest: "{{ cache_dir }}/hostname"
    follow: yes
