# Configure system settings

- name: modify hosts file
  template:
    src: hosts.j2
    dest: "/etc/hosts"
    follow: yes

- name: create hostname file
  template:
    src: hostname.j2
    dest: "/etc/hostname"
    follow: yes

- name: create bash aliases
  template:
    src: bash_aliases.j2
    dest: "{{ home_dir }}/.bash_aliases"
    follow: yes
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "u=rw"


#- name: update apt-get cache
#  apt:
#    force_apt_get: yes
#    update_cache: yes

- name: install packages
  apt: 
    force_apt_get: yes
    name: "{{ item }}"
    state: present
  loop: 
    - libnfs11 
    - nfs-common
    - zram-config