# Vars for all groups.

ansible_connection: ssh
ansible_port: 22
ansible_user: odroid
ansible_ssh_pass: odroid
ansible_become: yes
ansible_become_pass: "{{ ansible_ssh_pass }}"

nas: 192.168.1.54
drobo: 192.168.1.14

home_dir: /home/odroid
kodi_userdata_dir: "{{ home_dir }}/.kodi/userdata"

nas_movies: "{{ nas }}:/exports/Movies"
nas_series: "{{ nas }}:/exports/Series"

drobo_movies: "{{ drobo }}:/mnt/DroboFS/Shares/Public/Movies"
drobo_series: "{{ drobo }}:/mnt/DroboFS/Shares/Public/Series"
drobo_pictures: "{{ drobo }}:/mnt/DroboFS/Shares/Public/Pictures"
drobo_music: "{{ drobo }}:/mnt/DroboFS/Shares/Public/Music"