# Configure Kodi settings

- name: Create advanced settings file
  template:
    src: advancedsettings.xml.j2
    dest: "{{ kodi_userdata_dir }}/advancedsettings.xml"
    follow: yes
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"

#- name: Create GUI settings file
#  template:
#    src: guisettings.xml.j2
#    dest: "{{ kodi_userdata_dir }}/guisettings.xml"
#    follow: yes
#    group: "{{ ansible_user }}"
#    owner: "{{ ansible_user }}"
#    mode: "u=rw,g=r,o=r"


- name: Create sources file
  template:
    src: sources.xml.j2
    dest: "{{ kodi_userdata_dir }}/sources.xml"
    follow: yes
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"

